#!/usr/bin/env bun
/** Vendor the pinned upstream skill and MIT license into the app. No runtime downloads. */
import { writeFile } from "fs/promises";
import { resolve } from "path";

const commit = process.argv[2] ?? "225a6f39ac85f76ee48dbad772ea4abe4ed6c9d8";
if (!/^[a-f0-9]{40}$/.test(commit)) throw new Error("Pass a full upstream commit SHA.");
const base = `https://raw.githubusercontent.com/blader/humanizer/${commit}`;
const read = async (path: string) => {
  const response = await fetch(`${base}/${path}`);
  if (!response.ok) throw new Error(`${path}: HTTP ${response.status}`);
  return response.text();
};
const [skill, license] = await Promise.all([read("SKILL.md"), read("LICENSE")]);
const version = skill.match(/version:\s*"([^"]+)"/)?.[1];
if (!version || !skill.includes("## How to work") || !license.includes("MIT License")) throw new Error("Unexpected upstream format.");
const rules = skill.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, "").trim();
const target = resolve(import.meta.dir, "../src/bun/collab/agent/humanize");
await writeFile(`${target}/english-rulebook.ts`, `// Generated by scripts/sync-blader-humanizer.ts; do not edit.\n// blader/humanizer v${version} @ ${commit}, MIT (LICENSE.blader-humanizer).\nexport const ENGLISH_HUMANIZER_VERSION = ${JSON.stringify(version)};\nexport const ENGLISH_HUMANIZER_COMMIT = ${JSON.stringify(commit)};\nexport const ENGLISH_HUMANIZER_RULES = ${JSON.stringify(rules)};\n`);
await writeFile(`${target}/LICENSE.blader-humanizer`, license);
console.log(`Bundled blader/humanizer v${version} @ ${commit}`);
