#!/usr/bin/env bun
/**
 * Copies the im-not-ai ("Humanize KR") rulebooks into ScholarPen so the
 * humanizer ships inside the app. Run it after updating the im-not-ai checkout:
 *
 *   bun run sync:im-not-ai [path/to/im-not-ai]
 *
 * The path defaults to $IM_NOT_AI_DIR, then ../im-not-ai beside this repo.
 * Writes src/bun/collab/agent/humanize/rulebook.ts (generated, do not edit)
 * and the upstream MIT license next to it.
 */
import { existsSync } from "fs";
import { readFile, writeFile } from "fs/promises";
import { join, resolve } from "path";

const repoRoot = resolve(import.meta.dir, "..");
const source = resolve(process.argv[2] ?? process.env.IM_NOT_AI_DIR ?? join(repoRoot, "..", "im-not-ai"));
const references = join(source, "skills", "humanize-korean", "references");
if (!existsSync(references)) {
  console.error(`im-not-ai not found at ${source} (expected ${references}).`);
  process.exit(1);
}

const [quickRules, diagnosisRules, license, manifest] = await Promise.all([
  readFile(join(references, "quick-rules.md"), "utf-8"),
  readFile(join(references, "diagnosis-rules.md"), "utf-8"),
  readFile(join(source, "LICENSE"), "utf-8"),
  readFile(join(source, ".claude-plugin", "plugin.json"), "utf-8").then(JSON.parse),
]);
const commit = Bun.spawnSync(["git", "-C", source, "rev-parse", "--short", "HEAD"]).stdout.toString().trim() || "unknown";

const target = join(repoRoot, "src", "bun", "collab", "agent", "humanize");
await writeFile(join(target, "rulebook.ts"), `// Generated by scripts/sync-im-not-ai.ts — do not edit.
// Source: im-not-ai (Humanize KR) v${manifest.version} @ ${commit}, MIT License (see LICENSE.im-not-ai).

export const IM_NOT_AI_VERSION = ${JSON.stringify(manifest.version)};
export const IM_NOT_AI_COMMIT = ${JSON.stringify(commit)};

/** Slim rulebook the rewrite call works from (skills/humanize-korean/references/quick-rules.md). */
export const QUICK_RULES = ${JSON.stringify(quickRules)};

/** Every pattern with its detection signature, for the diagnosis call (references/diagnosis-rules.md). */
export const DIAGNOSIS_RULES = ${JSON.stringify(diagnosisRules)};
`);
await writeFile(join(target, "LICENSE.im-not-ai"), license);
console.log(`Synced im-not-ai v${manifest.version} @ ${commit} into ${target}`);
